using System.Collections.Generic;
using Godot;

namespace Ironvale.Game.Audio;

/// <summary>
/// Sound effects by logical id (res://assets/audio/SFX_&lt;id&gt;.tres, generated by tools/assets/build_audio.py), on the
/// "SFX" bus. Small player pools (UI and world), a per-id cooldown so bursts don't stack (UI_UX_guide §5.3: "com limite
/// de repetição"), and no-ops in headless runs. View only: never touches the simulation.
/// </summary>
public partial class Sfx : Node
{
    private const int Voices = 8;
    private const ulong CooldownMs = 45;

    private static Sfx? _instance;
    private readonly Dictionary<string, AudioStream?> _streams = new();
    private readonly Dictionary<string, float> _volumes = new();
    private readonly Dictionary<string, ulong> _lastPlayed = new();
    private readonly List<AudioStreamPlayer> _ui = new();
    private readonly List<AudioStreamPlayer3D> _world = new();
    private int _nextUi, _nextWorld;

    public override void _Ready()
    {
        _instance = this;
        if (FileAccess.GetFileAsString("res://assets/audio/sfx_volumes.json") is { Length: > 0 } json
            && Json.ParseString(json).AsGodotDictionary() is { } volumes)
            foreach (var (k, v) in volumes) _volumes[k.AsString()] = (float)v.AsDouble();
        for (int i = 0; i < Voices; i++)
        {
            var p = new AudioStreamPlayer { Bus = "SFX" };
            AddChild(p);
            _ui.Add(p);
            var p3 = new AudioStreamPlayer3D { Bus = "SFX", UnitSize = 30f, MaxDistance = 400f };
            AddChild(p3);
            _world.Add(p3);
        }
    }

    public override void _ExitTree()
    {
        if (_instance == this) _instance = null;
    }

    /// <summary>Plays a UI / non-positional sound.</summary>
    public static void Play(string id) => _instance?.PlayInternal(id, null);

    /// <summary>Plays a sound at a world position (heard relative to the camera).</summary>
    public static void PlayAt(string id, Vector3 position) => _instance?.PlayInternal(id, position);

    private void PlayInternal(string id, Vector3? at)
    {
        if (DisplayServer.GetName() == "headless") return;
        ulong now = Time.GetTicksMsec();
        if (_lastPlayed.TryGetValue(id, out ulong last) && now - last < CooldownMs) return;
        _lastPlayed[id] = now;
        if (!_streams.TryGetValue(id, out var stream))
        {
            string path = $"res://assets/audio/SFX_{id}.tres";
            stream = ResourceLoader.Exists(path) ? GD.Load<AudioStream>(path) : null;
            _streams[id] = stream;
        }
        if (stream is null) return;
        float db = _volumes.GetValueOrDefault(id, 0f);
        if (at is { } pos)
        {
            var p = _world[_nextWorld++ % Voices];
            p.Stream = stream;
            p.VolumeDb = db;
            p.GlobalPosition = pos;
            p.Play();
        }
        else
        {
            var p = _ui[_nextUi++ % Voices];
            p.Stream = stream;
            p.VolumeDb = db;
            p.Play();
        }
    }
}
